//
//  DisclaimerView.swift
//  Miracle
//
//  Created by Jacques Kounkou on 2026-08-07.
//

import Foundation
import SwiftUI

struct DisclaimerView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                Text("1. Informational and Educational Purposes Only")
                    .font(.headline)
                    .padding(.top, 12)
                
                JustifiedText(
                    text: "The physical performance forecasts, recovery boundaries, physiological adaptation windows, and training cycle tracking analyses generated by this application are derived entirely from mathematical algorithms, historical training density datasets, and the Miracle Inc. reasearch impulse-response models. All outputs, metrics, and insights are provided exclusively for informational, educational, and self-monitoring purposes. This software does not possess clinical intelligence, nor can it dynamically evaluate your real-world cardiovascular, metabolic, structural, or psychological state."
                )
                
                Text("2. Not a Substitute for Professional Medical Advice")
                    .font(.headline)
                    .padding(.top, 12)
                
                JustifiedText(
                    text: "The information, analytics, and auto-generated training suggestions presented within this dashboard are absolutely not intended to be, and must never be taken as a substitute for, professional medical advice, clinical diagnosis, predictive health screenings, or professional injury treatment. Athletics and high-intensity physical exertion carry inherent risks of severe acute injury, chronic overtraining syndrome, metabolic exhaustion, and cardiovascular stress.Never disregard professional medical advice, delay seeking evaluation from a qualified healthcare practitioner, or alter your prescribed rehabilitation routines because of an analytical insight, baseline chart line, or phase boundary timeline displayed within this application."
                )
                
                Text("3. Mandatory Professional Consultation")
                    .font(.headline)
                    .padding(.top, 12)
                
                JustifiedText(
                    text: "Before implementing any modifications to your current exercise routines, altering your training frequency, executing high-intensity interval training (HIIT), or attempting to target specific fatigue-clearance thresholds (such as the 36% metric or complete supercompensation windows), you must consult with a licensed healthcare professional, physician, cardiologist, or certified sports medicine specialist.A thorough clinical assessment is required to ensure your cardiovascular system and musculoskeletal integrity can safely absorb the physical stress scores calculated by this software."
                )
                
                Text("4. Assumption of Risk and Limitation of Liability")
                    .font(.headline)
                    .padding(.top, 12)
                
                JustifiedText(
                    text: "By utilizing this software to track, schedule, or forecast your athletic workouts, you explicitly acknowledge and agree that you are choosing to engage in physical activity entirely at your own risk. The creators, developers, and distributors of this application make no guarantees regarding the biological accuracy or absolute mathematical certainty of the underlying predictive formulas.Under no circumstances shall the platform or its developers be held liable for any direct, indirect, incidental, consequential, or punitive damages, including but not limited to physical injury, illnesses, medical emergencies, rhabdomyolysis, or overtraining setbacks resulting directly or indirectly from your reliance on the metrics provided herein."
                )
            }
            .padding(24)
        }
        .background(Color(.systemGroupedBackground))
        .navigationTitle("Disclaimer")
        .navigationBarTitleDisplayMode(.inline)
    }
}
